### ISSUE TITLE
content-src/styles/icons.scss points to non-existent SVG

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1057]
Ref: https://github.com/mozilla/activity-stream/pull/1039#discussion-diff-73756112

We have the following code in [/content-src/styles/icons.scss:66-68](https://github.com/mozilla/activity-stream/blob/78c4d84240335aab17f6720a0f3e5051afbf8e00/content-src/styles/icons.scss#L66-L68):

```css
  &.icon-showMore {
    background-image: url('img/glyph-show-more-16.svg');
  }
```

But there doesn't seem a file with that name, although suspiciously there is a _glyph-showmore-16.svg_ ("showmore" vs "show-more") at [/content-src/static/img/glyph-showmore-16.svg](https://github.com/mozilla/activity-stream/blob/330b1342938535425c9b74d8829542adaf3c796f/content-src/static/img/glyph-showmore-16.svg)
