### ISSUE TITLE
Use CircleCI for CI

### ISSUE THREAD

**Issue by oyiptong** [mozilla/activity-stream#148]
We're having random Xvfb issues on travis and this seems to be a fairly prevalent issue on travis for a few years.

The problem seems to occur randomly and without a clear solution available.

We should explore using CircleCI for CI instead.

**Comment by pdehaan** [comment]
Not sure if any of this helps: [**mozilla/fxa-content-server** /.travis.yml](https://github.com/mozilla/fxa-content-server/blob/master/.travis.yml):

```yaml
addons:
  firefox: "40.0"

before_install:
  # Setup the xvfb environment. Read more at http://docs.travis-ci.com/user/gui-and-headless-browsers/
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
```

https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI

... Or maybe not, since it looks like our [.travis.yml:8](https://github.com/mozilla/activity-streams/blob/317f3f8a5ab232109d051643112cb2586225eb14/.travis.yml#L8) is using a custom screen resolution and pretty much the same example on that Travis-CI page (plus the `-extension RANDR` flag).
