### ISSUE TITLE
Add info link to all sections.

### ISSUE THREAD

**Issue by rlr** [mozilla/activity-stream#3626]
After hacking up some ideas with @bryanbell, we decided we want to:

* have an info icon on all sections
* only show the icon on hover of the section
* add a link to the preferences sidebar from the info box
* only show the top sites edit link on hover of top sites

We want to uplift this for 57.

**Comment by rlr** [comment]
We will reuse all strings for 57 and make better strings for 58.

**Comment by Mardak** [comment]
```css
.sections-list .section-top-bar .section-info-option .info-option::before {
  content: "";
  display: block;
  height: 32px;
  left: 50%;
  position: absolute;
  right: 0;
  top: -32px;
}
```
Remove `transition-delay` use `$photon-easing: cubic-bezier(.07, .95, 0, 1);` for timing
