### ISSUE TITLE
Invisible space for info prevents clicking on Edit

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3631]
From #3628

Info open:
<img width="549" alt="image" src="https://user-images.githubusercontent.com/438537/31048261-90213dc2-a5ce-11e7-91f8-cc43e156660e.png">

Info closed:
<img width="431" alt="image" src="https://user-images.githubusercontent.com/438537/31048264-980f7814-a5ce-11e7-8300-db552d83ddc0.png">

**Comment by Mardak** [comment]
Also, it uses `left`/`right` instead of `offset-*`. Maybe it should just be a `width` and a `offset-inline-end`?

**Comment by AmyYLee** [comment]
Attached is a spec for information panels. I've added details for including a hairline and padding between "Edit" and the (?) icon.

https://mozilla.invisionapp.com/share/TUDPTAH8E

**Comment by Mardak** [comment]
@AmyYLee any guidance on the invisible space sizing? I suppose with the separator between Edit and (?), we could just assume the invisible space should be no wider than where the separator would be.

Also it looks like there is increased spacing from the section header to its content to allow for the doorhanger triangle. It sounded like the current doorhanger's position was decided to have equal "extra" spacing on the top and right edges. See top left corner and bottom right corner:

<img width="339" alt="image" src="https://user-images.githubusercontent.com/438537/31094383-da849bd8-a769-11e7-9b35-216ea2180949.png">

**Comment by AmyYLee** [comment]
"I suppose with the separator between Edit and (?), we could just assume the invisible space should be no wider than where the separator would be."

**Yes!**

Also it looks like there is increased spacing from the section header to its content to allow for the doorhanger triangle. It sounded like the current doorhanger's position was decided to have equal "extra" spacing on the top and right edges. See top left corner and bottom right corner:

**The current screenshot looks good to me. The spacing above shouldn't change with the addition of the triangle at the top.**

**Comment by Mardak** [comment]
Just jotting down some live edits to get this state based on feedback on slack. Have a hover grey-90 10% background for the (?) with 4px corner radius. Keep the original right offset while pushing down the top offset to make space for the arrow. This is with the 16px spacing as per #3634.

![pasted image at 2017_10_03 12_03 pm](https://user-images.githubusercontent.com/438537/31144124-9421a692-a834-11e7-9660-4a37a19b67b7.png)

```css
.section-top-bar .info-option-icon[aria-expanded="true"] {
    fill: rgba(12, 12, 13, 0.8);
    background-color: rgba(12,12,13,0.1);
    border-radius: 4px;
    box-shadow: 0 0 0 5px rgba(12,12,13,0.1);
}
.section-top-bar .section-info-option .info-option::before {
    content: "";
    display: block;
    height: 32px;
    position: absolute;
    right: 0;
    top: -32px;
    background-image: url(chrome://global/skin/arrow/panelarrow-vertical@2x.png);
    background-repeat: no-repeat;
    background-size: 18px 10px;
    background-color: transparent;
    background-position: 15px bottom;
    width: 40px;
}
```

Also, the image is a `png` on mac but svg elsewhere…
https://searchfox.org/mozilla-central/search?q=panelarrow-vertical&path=popup.css
