### ISSUE TITLE
Center the details page’s main content when possible

### ISSUE THREAD

**Issue by fvsch** [mozilla/activity-stream#692]
I’m talking about the main content in the “All” and “Bookmarks” pages. Currently it’s left aligned.

When going from the New Tab view to this one on a screen at least 1300px wide, you end up with similar content that jumps visually (to the left). It might be nicer to have a more similar experience, with the main content being horizontally centered when there’s enough room.

By the way I mean centered in the viewport, not in its container. Quick test:

``` css
@media (min-width: 1240px) {
  main.timeline section.content {
    margin-left: 0;
  }
  main.timeline .wrapper {
    margin-left: auto;
    margin-right: auto;
  }
}
```

On 13" laptops it might be visual polish, but on wider screens the left alignment is really jarring.

PS: the `.wrapper`'s max-width seems a bit off. 688px but top content is roughly 700px.
